name: besafe_app
description: BeSafe Worker Safety Monitoring Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # HTTP requests (useful if backend API is added later)
  http: ^1.2.0

  # ONNX Runtime for running the AI model locally
  onnxruntime: ^1.4.1

  # Charts for physiological data visualization
  fl_chart: ^0.66.2

  # State management (simple and lightweight)
  provider: ^6.1.2

  # Utility for handling async streams (useful for realtime data)
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/models/random_forest_wesad.onnx